name: Update badges

on:
  workflow_dispatch:
  schedule:
    # Runs at 15 UTC
    - cron: "0 15 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: joaopinto15/badge-readme@main
        with:
          COMMIT_MESSAGE: "Updated badges" # optional
          CREDLY_SORT: POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: 80 # optional, 110x110 default
